name: 'Changie Action'
description: 'Run Changie commands as part of a GitHub action workflow'
author: 'miniscruff'
branding:
  color: 'purple'
  icon: 'package'

inputs:
  version:
    description: 'Changie version'
    default: 'latest'
    required: false
  args:
    description: 'Arguments to pass to Changie'
    required: true

outputs: {}

runs:
  using: 'node16'
  main: 'dist/index.js'
